// ─── COLOUR TOKENS ────────────────────────────────────────────────────────────
// Primary: #229814 (vivid green)  |  Accent: #F0F49C (lime yellow)

export const C = {
  // Greens
  greenDark:    "#0D4A08",
  greenMid:     "#186010",
  greenSage:    "#229814",
  greenLight:   "#4DB840",
  greenPale:    "#A8DCA3",
  greenMint:    "#E0F5DE",

  // Lime-Yellows
  yellowDeep:   "#6B7005",
  yellowWarm:   "#C8CC18",
  yellowMid:    "#D8DC50",
  yellowPale:   "#F0F49C",
  yellowCream:  "#F8FADA",

  // Neutrals
  bgPage:       "#F3F8F2",
  bgCard:       "#FFFFFF",
  bgCardHover:  "#F0F8EF",
  text:         "#0D2B0B",
  textMid:      "#2A4A28",
  textMuted:    "#5A7558",
  border:       "#C8E0C5",
  borderStrong: "#95C490",

  // Host-only gender colours
  female:       "#D06070",
  male:         "#4A7FBB",
};

// ─── NAVIGATION ───────────────────────────────────────────────────────────────
export const NAV = [
  { icon: "◉",  label: "Dashboard",   id: "home",     roles: ['user', 'host', 'admin'] },
  { icon: "⊞",  label: "Discover",    id: "discover", roles: ['user', 'host', 'admin'] },
  { icon: "📋", label: "My Events",   id: "myevents", roles: ['host', 'admin'] },
  { icon: "⚙",  label: "Admin Panel", id: "admin",    roles: ['admin'] },
];

// ─── CATEGORIES ───────────────────────────────────────────────────────────────
export const CATEGORIES = [
  "All",
  "🏸 Badminton",
  "🎾 Tennis",
  "🧘 Yoga",
  "🚴 Cycling",
  "🎵 Music",
  "🎨 Art",
  "🏃 Running",
  "📸 Photography",
  "🍳 Cooking",
  "🕺 Dance",
  "🧗 Climbing",
];

// ─── MOCK EVENT DATA ──────────────────────────────────────────────────────────
// In production these come from your Supabase database via the API.
export const EVENTS = [
  {
    id: 1,
    title: "Badminton Social Doubles",
    host: "SportHub Jakarta",
    hostVerified: true,
    date: "Sat, 15 Mar 2025",
    time: "08:00–11:00 WIB",
    location: "GOR Senayan, Jakarta Pusat",
    price: 75000,
    category: "🏸 Badminton",
    totalSlots: 16,
    totalFilled: 11,
    gender: { female: { filled: 5, max: 8 }, male: { filled: 6, max: 8 } },
    tags: ["Mixed", "All levels", "Indoor"],
    rating: 4.8,
    reviews: 42,
    desc: "Weekly mixed doubles session for all skill levels. Shuttlecock and court rental included. Great way to meet new people!",
  },
  {
    id: 2,
    title: "Morning Yoga in the Park",
    host: "ZenMove",
    hostVerified: true,
    date: "Sun, 16 Mar 2025",
    time: "06:30–08:00 WIB",
    location: "Taman Suropati, Menteng",
    price: 50000,
    category: "🧘 Yoga",
    totalSlots: 20,
    totalFilled: 14,
    gender: { female: { filled: 12, max: 16 }, male: { filled: 2, max: 4 } },
    tags: ["Women-Friendly", "Outdoor", "Beginner OK"],
    rating: 4.9,
    reviews: 88,
    desc: "Start your Sunday right with mindful flow yoga surrounded by nature. Bring your own mat. Light stretching warm-up included.",
  },
  {
    id: 3,
    title: "Urban Photography Walk",
    host: "FrameCity",
    hostVerified: false,
    date: "Sat, 15 Mar 2025",
    time: "16:00–19:00 WIB",
    location: "Kota Tua, Jakarta Barat",
    price: 120000,
    category: "📸 Photography",
    totalSlots: 12,
    totalFilled: 9,
    gender: { female: { filled: 5, max: 6 }, male: { filled: 4, max: 6 } },
    tags: ["Creative", "Outdoor", "DSLR / Phone OK"],
    rating: 4.7,
    reviews: 31,
    desc: "Explore the colonial streets of Kota Tua while learning composition, golden hour light, and street photography technique.",
  },
  {
    id: 4,
    title: "Electric Guitar Jam Session",
    host: "StringTheory",
    hostVerified: true,
    date: "Fri, 14 Mar 2025",
    time: "19:00–22:00 WIB",
    location: "Kemang Studio, Jakarta Selatan",
    price: 100000,
    category: "🎵 Music",
    totalSlots: 10,
    totalFilled: 7,
    gender: { female: { filled: 3, max: 5 }, male: { filled: 4, max: 5 } },
    tags: ["Intermediate", "Indoor", "Equipment Provided"],
    rating: 4.6,
    reviews: 19,
    desc: "Monthly jam night for intermediate guitarists. We'll work through classic riffs and improvise together. Amps and guitars available.",
  },
  {
    id: 5,
    title: "Sunday Cycling — Sentul Loop",
    host: "VeloJakarta",
    hostVerified: true,
    date: "Sun, 16 Mar 2025",
    time: "05:30–10:00 WIB",
    location: "Sentul City, Bogor",
    price: 85000,
    category: "🚴 Cycling",
    totalSlots: 30,
    totalFilled: 18,
    gender: { female: { filled: 7, max: 12 }, male: { filled: 11, max: 18 } },
    tags: ["Intermediate", "Outdoor", "Scenic Route"],
    rating: 4.9,
    reviews: 67,
    desc: "50km scenic loop around the Sentul highlands. Support vehicle included. Ideal for road bike riders. Breakfast stop mid-ride.",
  },
  {
    id: 6,
    title: "Batik Painting Workshop",
    host: "KaryaNusantara",
    hostVerified: false,
    date: "Sat, 22 Mar 2025",
    time: "10:00–13:00 WIB",
    location: "Kemang Art Space, Jakarta",
    price: 180000,
    category: "🎨 Art",
    totalSlots: 14,
    totalFilled: 5,
    gender: { female: { filled: 4, max: 10 }, male: { filled: 1, max: 4 } },
    tags: ["Creative", "Indoor", "Materials Included"],
    rating: 4.5,
    reviews: 12,
    desc: "Learn traditional Indonesian batik from a certified artisan. All materials and a 40×60cm canvas included to take home.",
  },
];
